site_name: Windows Active Directory Security
site_url: https://mydomain.org/netexperiments/wadsecurity
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - navigation.indexes
    - navigation.expand
    - navigation.tabs.sticky
nav:
  - Home: index.md
  - Multi-domain AD Lab:
    - Lab setup: labs/multi-domain-attacks/lab-setup.md
    - Reconnaissance And Discovery:
      - Network reconnaissance: labs/multi-domain-attacks/Network-Reconnaissance.md
      - Anonymous AD reconnaissance: labs/multi-domain-attacks/AD-Reconnaissance.md
      - User enumeration: labs/multi-domain-attacks/user-enumeration.md
    - Initial Credential Access: 
      - Password spraying: labs/multi-domain-attacks/password-spraying.md
      - AS-REP Roasting: labs/multi-domain-attacks/AS-REPRoasting.md
      - Kerberoasting: labs/multi-domain-attacks/Kerberoasting.md
      - LLMNR poisoning: labs/multi-domain-attacks/LLMNR-poisoning.md
    - Lateral Movement and Relay:
      - Authenticated AD Reconnaissance: labs/multi-domain-attacks/LDAPDump.md
      - NTLM relay to SMB: labs/multi-domain-attacks/NTLMrelaySMB.md
      - Drop the MIC: labs/multi-domain-attacks/DropTheMIC.md
      - MSSQL Abuse: labs/multi-domain-attacks/MSSQL.md
      - IIS Abuse: labs/multi-domain-attacks/IIS.md
    - Privilege Escalation:
      - Local Privilege Escalation: labs/multi-domain-attacks/LocalPrivilegeEscalation.md
      - Unconstrained delegation abuse: labs/multi-domain-attacks/unconstrained-delegation-abuse.md
      - Constrained delegation abuse: labs/multi-domain-attacks/ConstrainedDelegationAbuse.md
      - RBCD Abuse: labs/multi-domain-attacks/RBCDAbuse.md
      - SAMAccountName Spoofing: labs/multi-domain-attacks/SAMAccountNameSpoofing.md
      - PrintNightmare: labs/multi-domain-attacks/PrintNightmare.md
      - BloodHound: labs/multi-domain-attacks/BloodHound.md
      - ACL Abuse: labs/multi-domain-attacks/ACLAbuse.md
      - GPO Abuse: labs/multi-domain-attacks/GPOabuse.md
      - ADCS abuse: labs/multi-domain-attacks/ADCSExploiting.md
    - Domain Extraction And Persistence:
      - DCSync: labs/multi-domain-attacks/DCSync.md
      - Golden Tickets: labs/multi-domain-attacks/GoldenTickets.md
    - Cross-Domain and Forest Expansion: 
      - Trust Reconnaissance: labs/multi-domain-attacks/Trust-Reconnaissance.md
      - Trustpocalypse: labs/multi-domain-attacks/Trustpocalypse.md 
      - Forging Trust Tickets: labs/multi-domain-attacks/ForgingTrustTickets.md
      - Forest Trusts Attack: labs/multi-domain-attacks/ForestTrustsAttack.md
    - Domain Controller configuration using GUI: 
      - Example of DC configuration: labs/dc-configuration.md
  - Single-domain AD Lab:  
    - Lab setup: labs/single-domain-attacks/lab-setup.md
    - Reconnaissance and Discovery:
      - Network reconnaissance: labs/single-domain-attacks/Network-Reconnaissance.md
      - Anonymous AD reconnaissance: labs/single-domain-attacks/AD-Reconnaissance.md
      - User enumeration: labs/single-domain-attacks/user-enumeration.md
    - Initial Credential Access: 
      - Password spraying: labs/single-domain-attacks/password-spraying.md
      - AS-REP Roasting: labs/single-domain-attacks/AS-REPRoasting.md
      - Kerberoasting: labs/single-domain-attacks/Kerberoasting.md
      - LLMNR poisoning: labs/single-domain-attacks/LLMNR-poisoning.md
    - Lateral Movement and Relay: 
      - Authenticated AD Reconnaissance: labs/single-domain-attacks/LDAPDump.md
      - NTLM relay to SMB: labs/single-domain-attacks/NTLMrelaySMB.md
      - Drop the MIC: labs/single-domain-attacks/DropTheMIC.md
      - MSSQL Abuse: labs/single-domain-attacks/MSSQL.md
      - IIS Abuse: labs/single-domain-attacks/IIS.md
    - Privilege Escalation:
      - Local Privilege Escalation: labs/single-domain-attacks/LocalPrivilegeEscalation.md
      - Unconstrained delegation abuse: labs/single-domain-attacks/unconstrained-delegation-abuse.md
      - Constrained delegation abuse: labs/single-domain-attacks/ConstrainedDelegationAbuse.md
      - RBCD Abuse: labs/single-domain-attacks/RBCDAbuse.md
      - SAMAccountName Spoofing: labs/single-domain-attacks/SAMAccountNameSpoofing.md
      - PrintNightmare: labs/single-domain-attacks/PrintNightmare.md
      - BloodHound: labs/single-domain-attacks/BloodHound.md
      - ACL Abuse: labs/single-domain-attacks/ACLAbuse.md
      - GPO Abuse: labs/single-domain-attacks/GPOabuse.md
      - ADCS abuse: labs/single-domain-attacks/ADCSExploiting.md
    - Domain Extraction And Persistence:
      - DCSync: labs/single-domain-attacks/DCSync.md
      - Golden Tickets: labs/single-domain-attacks/GoldenTickets.md
    - Domain Controller configuration using GUI: 
      - Example of DC configuration: labs/dc-configuration.md
  - Active Directory Extended Report: report.md
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences    
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra_javascript:
  - js/pass_spray_interactive_answer.js